### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by zenorocha** [brunoziie/time-ago-element#6]
In order to fix https://github.com/customelements/customelements.io/issues/34 and appear `time-ago` in the website instead of the old `timeago` name, you need to rename this repo to `time-ago` or `time-ago-element`.

**Comment by brunoziie** [comment]
Repository renamed

**Comment by zenorocha** [comment]
Demo link on README wasn't fixed.

**Comment by brunoziie** [comment]
fixed
